services:
  robrowser-remote-client-api:
    env_file:
      - .env
    image: ro-remote-client-php:latest
    volumes:
      - ./:/var/www/html
      - ./resources:/var/www/html/resources
      - ./data:/var/www/html/data
      - ./System:/var/www/html/System
      - ./BGM/var/www/html/BGM
    ports:
      - "80:80"

